// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmYgJ6xx0UtJusASPMq1KGI00EZNAZdM',
    appId: '1:22658523576:web:fa6b338ba846b494b26f4d',
    messagingSenderId: '22658523576',
    projectId: 'esp32cam-application',
    authDomain: 'esp32cam-application.firebaseapp.com',
    storageBucket: 'esp32cam-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJOSrV8AK1T50b-BVO270EDpRIJJV8Nk',
    appId: '1:22658523576:android:fc3f924bc8d0d0eab26f4d',
    messagingSenderId: '22658523576',
    projectId: 'esp32cam-application',
    storageBucket: 'esp32cam-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJEwL-c2SXhgNVRgHkvV9Zk-obyGfCOw',
    appId: '1:22658523576:ios:1303b783d08d9278b26f4d',
    messagingSenderId: '22658523576',
    projectId: 'esp32cam-application',
    storageBucket: 'esp32cam-application.appspot.com',
    iosBundleId: 'com.example.perview',
  );
}
